
package com.comcast.admgmt.framework;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-16T06:57:35.599-06:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "ServiceException", targetNamespace = "http://framework.admgmt.comcast.com/model")
public class ServiceException extends Exception {
    
    private com.comcast.admgmt.framework.model.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.comcast.admgmt.framework.model.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.comcast.admgmt.framework.model.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.comcast.admgmt.framework.model.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
